### ISSUE TITLE
strict_slashes is not respected from the application level

### ISSUE THREAD

**Issue by yury-stepanov** [huge-success/sanic-openapi#102]
By setting global configuration option `strict_slashes` to True I would expect to swagger documentation no to have duplicate entries that differentiate only in trailing slash. Example:

```
app = sanic.Sanic(strict_slashes=True)

test_blueprint = sanic.Blueprint("test")

# no strict_slashes here
@test_blueprint.route("/test", methods=["GET"])
def test(request):
    return "Hello world"

app.blueprint(swagger_blueprint)
app.blueprint(test_blueprint)
```

**Comment by chenjr0719** [comment]
Hi there,

About `strict_slashes`, I think this is a bug(or feature maybe) of Sanic.
Try this:
```python
for route in app.router.routes_all:
    print(route)
```

Output:
```
/swagger
/swagger/swagger.json
/swagger/swagger.json/
/swagger/swagger-config
/swagger/swagger-config/
/swagger/
/swagger/<file_uri:/?.+>
/swagger/<file_uri:/?.+>/
/test
/test/
```

You can see that Sanic did not apply app's `strict_slashes` to any blueprint. I' going to close this issue and open a new one at the repository of Sanic.
