### ISSUE TITLE
One decorator to wrap potentially all route decorators including route registration and doc

### ISSUE THREAD

**Issue by volfpeter** [huge-success/sanic-openapi#107]
When documenting a route, we typically have to add an `app.route` decorator, then a set of `sanic-openapi` decorators, then authorization, cors, request or response transformer decorators, and so on. The resulting code is hard to read and not that good to look at.

I've implemented a `sanic-openapi`-based decorator factory class that can be used for documenting routes (and even registering them in the `Sanic` app or blueprint, or adding extra decorators to them) with a single line of code (a single decorator). I would be happy to commit it to this project if this is something you're interested in.

Here is an example code, `API` is the decorator factory class I implemented (route documentation classes must be derived from this base class):

```Python
# This is the actual class that documents the route.
class Data(API):
    class consumes:
        stg = str

# This Data extension adds the first and second decorators as well to the decorated route.
class DecoratedData(Data):
    decorators = (first, second)

# Below are example routes, all of which have the exact same behavior.
# --------------------------------------

@DecoratedData.get(app, "/data")
def data_all_in_one(request: Request):
    return "data"

@app.get("/data")
@DecoratedData
def data_doc_and_decorators_in_one(request: Request):
    return "data"

@Data.get(app, "/data")
@first
@second
def data_routing_and_doc_in_one(request: Request):
    return "data"

@app.get("/data")
@Data
@first
@second
def data(request:Request):
    return "data"

@app.get("/data")
@doc.consumes({"stg": str})
@first
@second
def data(request:Request):
    return "data"
```

I understand if this is not something you would like to have in the project.
On the other hand, if you are interested, then I'll submit a pull request so you can a have look at the code and get a better understanding of what it actually does.

**Comment by chenjr0719** [comment]
Wow, I have to say, it looks pretty cool. When I developing my company product, my decorators will be much longer than my handler function. I think your decorator factory class can totally save my code base. As a user of `sanic` and other plugins, I will buy it without a doubt.

And, as a contributor of `sanic-openapi`, I also buy it because this project supports multiple responses now. This is a well-documented route might look like:
```python
@app.post('/foo')
@doc.consumes(ConsumedModel, content_type='application/json', location='body', required=True)
@doc.produces(ProducedModel, content_type='application/json')
@doc.response(400, ...)
@doc.response(401, ...)
@doc.response(409, ...)
async def create_foo(request):
    ...

``` 

In this case, your decorator factory class will be a very attractive tool to help people use `sanic-openapi`, I think.

**Comment by volfpeter** [comment]
Well, one thing that's still missing is the support of the `response()` decorator... We wouldn't use it, as our APIs return HTTP 200 with either i) an error code and message or a proper result, or ii) an internal server error. Nevertheless, i wanted to add support for it just for the sake of completeness anyway. I'll make a decision on that part of the API and implement it next week.

I have one more question. Where would you like to have this class within `sanic-openapi`? The `API` class is about 350 lines of code (including lots of documentation and examples) right now and it will grow a bit more. I think it shouldn't be in the `doc` module, I currently have in an an `api` module. If that's ok, i'll submit a PR with the initial version.

**Comment by volfpeter** [comment]
I've submitted this feature in PR #111 (`doc.response()` support is also there in the PR).

**Comment by volfpeter** [comment]
@chenjr0719 @ahopkins Thanks guys!
I have just one more question before closing the issue: when can we expect the next release?

**Comment by volfpeter** [comment]
Hi @chenjr0719 @ahopkins !
Could you please give some feedback on when do plan to create the next release of `sanic-openapi`?

**Comment by chenjr0719** [comment]
@volfpeter Oops, my bad. I'm thinking about release new version `0.7.0` this month after I complete the new docs on readthedocs. This might be earlier if I can get the docs done this weekend.

@ahopkins What do you think?

**Comment by volfpeter** [comment]
No problem! And thanks for the info!

**Comment by ahopkins** [comment]
:+1:  to what @chenjr0719 says
