### ISSUE TITLE
Remove duplicate routes from doc

### ISSUE THREAD

**Issue by volfpeter** [huge-success/sanic-openapi#114]
`app.router.routes_all` contains 2 versions of all routes: one with a trailing `/` and one without it, see `sanic_openapi.swagger.build_spec()` (line 96 `for uri, route in app.router.routes_all.items(): ...`).

I think it's unnecessary to show both routes in the documentation. Would it be possible to keep only one version? I would personally prefer to keep the one without the trailing `/`, but maybe it would be best to make it configurable.

```Python
for uri, route in app.router.routes_all.items():
    if len(uri) > 1 and uri.endswith("/"):
        continue
    ...
```

**Comment by chenjr0719** [comment]
This is a good idea. I always use `strict_slashes=True` to avoid duplicate routes in swagger. If we can handle this problem, it would be very nice. About keep the `/` or not, I think make it configurable and default to keep `/` would be nice.

**Comment by volfpeter** [comment]
I was thinking about the default setting and decided to keep URIs without the trailing `/` by default. My reasoning is that in my experience users typically write URIs without the trailing `/` in the code (be it routing or URL building). Also, `strict_slashes` is not the default in Sanic, so making this URI version the default in the documentation didn't feel quite right.

**Comment by volfpeter** [comment]
PR is merged, so i'll close the issue if you don't mind.

**Comment by ahopkins** [comment]
thanks
