### ISSUE TITLE
[Bug] Global variables in module

### ISSUE THREAD

**Issue by chenjr0719** [huge-success/sanic-openapi#117]
**Describe the bug**
After adding more tests in this project. I found there are some weird global variables in this module:

* doc.definitions
https://github.com/huge-success/sanic-openapi/blob/cbf0f5b27fb6b56be048a8ef020b0082ac484543/sanic_openapi/doc.py#L108
* doc.route_specs
https://github.com/huge-success/sanic-openapi/blob/cbf0f5b27fb6b56be048a8ef020b0082ac484543/sanic_openapi/doc.py#L222
* swagger._spec
https://github.com/huge-success/sanic-openapi/blob/cbf0f5b27fb6b56be048a8ef020b0082ac484543/sanic_openapi/swagger.py#L29
* swagger.swagger_blueprint
https://github.com/huge-success/sanic-openapi/blob/cbf0f5b27fb6b56be048a8ef020b0082ac484543/sanic_openapi/swagger.py#L13

The `sanic_openapi` will use those variable to create a swagger.json. But all variables can not be controlled by users. In most case, I think this might not be a problem. However, this still not a good implement, I think.

**Screenshots**
None

**To Reproduce**
```python
from sanic import Sanic
from sanic.response import text

from sanic_openapi import doc, swagger_blueprint

app = Sanic()
app.blueprint(swagger_blueprint)


class Foo:
    id = int


class Bar:
    id = int


@app.post("/")
@doc.consumes(Foo)
def foo(request):
    return text("test")


_, resp = app.test_client.get("/swagger/swagger.json")
print(resp.json)

assert 'Foo' in resp.json['definitions']

app = Sanic()
app.blueprint(swagger_blueprint)


@app.post("/")
@doc.consumes(Bar)
def bar(request):
    return text("test")


_, resp = app.test_client.get("/swagger/swagger.json")
print(resp.json)

assert 'Bar' in resp.json['definitions']
assert 'Foo' not in resp.json['definitions'] # This will raise AssertionError

```

**Expected behavior**
Do not use global variables in this module. Maybe consider using factory pattern to create new swagger_blueprint every time.
```python
from sanic_openapi import SwaggerDocument

.
.
.

swagger_blueprint = SwaggerDocument.to_blueprint()
app.blueprint(swagger_blueprint)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: firefox
 - Version: [master](cbf0f5b27fb6b56be048a8ef020b0082ac484543)

**Additional context**
None

**Comment by AtomsForPeace** [comment]
Reopen?

**Comment by AtomsForPeace** [comment]
@chenjr0719 are you able to reopen this and maybe look at the pull request?

**Comment by chenjr0719** [comment]
@AtomsForPeace Sure, I will review the PR at the end of today. It is a little busy recent days.

**Comment by AtomsForPeace** [comment]
I was thinking maybe doing something along the lines of this: https://flask.palletsprojects.com/en/1.1.x/patterns/appfactories/#factories-extensions

One issue would be backwards compatibility.

The swagger.py file has a lot changed in it. Still have to figure out how to fix the definitions and route_specs that come out of doc.py
