### ISSUE TITLE
Swagger ui options doesn't have any effect

### ISSUE THREAD

**Issue by canberkkoc** [huge-success/sanic-openapi#119]
**Describe the bug**
SWAGGER_UI_CONFIGURATION = {
    'validatorUrl': None,
    'displayRequestDuration': True
} 
doesn't have any effect on swagger ui.

**Screenshots**
![s1](https://user-images.githubusercontent.com/5826958/60597408-8fdf6580-9db3-11e9-8021-30bba076acc3.png)
![s2](https://user-images.githubusercontent.com/5826958/60597327-67f00200-9db3-11e9-8cfc-be27c20ef922.png)
![s3](https://user-images.githubusercontent.com/5826958/60597331-69b9c580-9db3-11e9-9f7b-75d0911c5064.png)
**To Reproduce**
I use it as described on Readme file.

**Expected behavior**
I expected validation will turn off and see see display duration.

**Environment (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version : 0.5.3

**Comment by chenjr0719** [comment]
Hi @canberkkoc 

We haven't released the new version with Swagger-UI configuration feature on PyPI. If you want to use this feature, please use the master branch.

To install `sanic-openapi` with master branch, you can use this command:
```
$ pip install git+https://github.com/huge-success/sanic-openapi.git
```

I'm going to close this issue, feel free to add more feedback or reopen if you want.
