### ISSUE TITLE
Does not appear to work with class based routing

### ISSUE THREAD

**Issue by tclarke** [huge-success/sanic-openapi#12]
```class MyView(HTTPMethodView):
  @doc.summary("This is my view's getter")
  async def get(self, _):
    return response.json({'foo': []})
```

Does not include the summary.

**Comment by travisbrady** [comment]
I'm also interested in this. Any help I can provide? Pointers on where to start maybe?

**Comment by Typhon66** [comment]
Right now this doens't support class-based routing. Would like to add it in at some point. If anyone wants to do the work would be glad to merge a PR. If not i'll add it to the list of things to do.
