### ISSUE TITLE
upload file by swagger

### ISSUE THREAD

**Issue by yangmingbai** [huge-success/sanic-openapi#123]
I want to upload a file by swagger, but don't know how to use @doc.consumes define a file type 
like this..
`@doc.consumes({"myfile":` '',},location="multipart/form-data")`
  
![image](https://user-images.githubusercontent.com/51049448/62095391-e22c7d00-b2b2-11e9-8940-482de3ccfbcf.png)

**Comment by chenjr0719** [comment]
Hi @yangmingbai 

Please install `sanic-openapi` from master branch and try this:

```python
from sanic import Sanic
from sanic.response import json

from sanic_openapi import doc, swagger_blueprint

app = Sanic()
app.blueprint(swagger_blueprint)


@app.post("/test")
@doc.consumes(
    doc.File(name="file"), location="formData", content_type="multipart/form-data"
)
@doc.produces({"size": doc.Integer(), "type": doc.String()})
async def test(request):
    file = request.files.get("file")
    size = len(file.body)
    return json({"size": size, "type": file.type})

```

The swagger will look like:
![file](https://user-images.githubusercontent.com/13619684/62145157-82bb8500-b325-11e9-911e-ddf03808f448.png)

I'm going to close this issue. Feel free to add more feedbacks or reopen this issue if need.
