### ISSUE TITLE
Compatibility with Sanic 19.6.2

### ISSUE THREAD

**Issue by tng10** [huge-success/sanic-openapi#127]
Hi,

**Describe the bug**

I just bumped into an error when upgrading to newest version of Sanic using ASGI interface.

Since ASGI lifespan protocol has support for only two server events, we no longer can make usage of `before_server_start` and `after_server_stop` server events.

Sanic OpenAPI uses `before_server_start` server event and this give us the following warning:

```
UserWarning: You have set a listener for "before_server_start" in ASGI mode. It will be executed as early as possible, but not before the ASGI server is started.
```

**To Reproduce**
Run Sanic using an ASGI interface

**Expected behavior**
Make sure this warning doesn't happen.

**Environment:**
 - ubuntu 18.04
 - Version [0.5.3]

On the decorator of the method `build_spec` at the file `swagger.py` I suggest the following change:

**before**
```
@blueprint.listener('before_server_start')
```

**after**
```
@blueprint.listener('after_server_start')
```

What do you think about it?

**Comment by chenjr0719** [comment]
Sounds good. Would you wanna submit a PR for this?

**Comment by tng10** [comment]
Yes, I'll do it.

**Comment by tng10** [comment]
@chenjr0719 I just created PR #130 for it

**Comment by ahopkins** [comment]
:+1:  Nice catch.
