### ISSUE TITLE
[Feature Request] Support typehinting

### ISSUE THREAD

**Issue by viniciusd** [huge-success/sanic-openapi#128]
**Problem**
I'm always frustrated when I want to type-hint my models because `sanic-openapi` picks up the model types by assignment (e.g. `id = int`) only. However, I want to have a fully type hinted project.
It would be very nice to provide some code snippet to explain your use case.

We currently support:
```
class Car:
    make = str
    model = str
    year = int
```
It would be super handy in order to have a type hinted project, supporting:
```
class Car:
    make: str
    model: str
    year: int
```
**Solution**
It would be very nice to have a fallback to type hinting when building the models.
`typing.get_type_hints` might be our friend here.

**Progress**

- [ ] Make it testable and add tests
- [x] Support primitives #129 
- [x] Support typed dicts #134 
- [x] Support sequences #136 
- [ ] Support unions and optionals (which are unions)
- [ ] Support Sanic-OpenAPI's fields

**Comment by viniciusd** [comment]
As far as I browsed sanic-openapi's code, this shouldn't be too complicated. I should give it a try and open a PR if the idea is welcome

**Comment by chenjr0719** [comment]
I think this is a nice idea and any PR is welcome. :smile:
Furthermore, is this typehinting also support Sanic-OpenAPI's fields (e.g., `doc.String`)?

**Comment by viniciusd** [comment]
It _might_ support Sanic-OpenAPI's fields with further changes, like making Fields type hints.

I have added initial support for picking up type hints changing one line (+ two imports) and should be submitting a pull request in the next couple minutes.

I am more than willing to take type hinting support further and make this issue a tracking issue for that. Some of the next steps that come to mind are:
1. Support [type hinting] sequences
2. Support unions and optionals (which are unions)
3. Support Sanic-OpenAPI's fields

**Comment by viniciusd** [comment]
A fully working and minimal example of what I proposed is:
```
from sanic import Sanic
from sanic_openapi import doc, swagger_blueprint

app = Sanic()
app.blueprint(swagger_blueprint)

class Car:
    make: str
    model: str
    year: int

@app.get("/car/<id:int>")
@doc.summary("Gets a car")
@doc.produces(Car)
async def get_garage(request, car_id):
    return json({
        "spaces": 2,
        "cars": [{"make": "Nissan", "model": "370Z"}]
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```
Note this works with my first PR

**Comment by viniciusd** [comment]
Thoughts here @chenjr0719? That's actually blocking me from using sanic-openapi. Provisional support provided by #129

**Comment by viniciusd** [comment]
Great reminder, stale bot

**Comment by chenjr0719** [comment]
Hi @viniciusd, do you have other ideas about this issue? If not, I think it is fine to close it. :smiley:
