### ISSUE TITLE
[Bug] Documentation site returns a 404

### ISSUE THREAD

**Issue by jacebrowning** [huge-success/sanic-openapi#132]
https://sanic-openapi.readthedocs.io as mentioned in the README returns a 404.

**Comment by chenjr0719** [comment]
It's my fault. The documentation site still not ready but I put the URL on `README.md`.

@ahopkins Could you set up the new Readthedocs project for Sanic-OpenAPI? I will be very appreciated.

**Comment by ahopkins** [comment]
Will do. I have had a busy end to my Summer. I will dig into this in a few days.

**Comment by DerMika** [comment]
Any update on this?

**Comment by VMAtm** [comment]
Hello, what happened with the docs?

**Comment by chenjr0719** [comment]
I don't have enough permission to create Readthedocs project with this repository(this requires to create a webhook in this project). So, I'm waiting for @ahopkins to handle this. And I think he is very busy in recent months. :sweat_smile:

**Comment by notnami** [comment]
It seems like more than one person should have permission to publish to readthedocs to avoid this kind of scenario.

**Comment by chenjr0719** [comment]
@seemethere Just wondering if you have the permissions of this repository or not. We need a Readthedocs project to host the document. But I can not reach @ahopkins in recent months so this requirement has been pending for a long time. Could you help me to create a new Readthedocs project with this repository if you have the permissions? I will be very very very appreciated.

**Comment by ahopkins** [comment]
Yikes... so sorry everyone.

I added this and @chenjr0719 is listed as a maintainer.

https://readthedocs.org/projects/sanic-openapi/

Let me know what else is needed. I am back from being .... "absent".

**Comment by chenjr0719** [comment]
@ahopkins Welcome back and thanks for your helping.

The document site works now so I'm going to close this issue.
