### ISSUE TITLE
[Bug] File input is not rendered

### ISSUE THREAD

**Issue by artemnesterenko** [huge-success/sanic-openapi#133]
I'm trying to document my api for file uploading, but a file field is not rendered in the generated swagger. Here is a code example:
```python
@app.post("/file")
@doc.consumes(
        doc.File(name="file"), location="formData", content_type="multipart/form-data"
    )
def file(request):
    pass
```
Here is a screenshot of the generated documentation:
![Снимок экрана от 2019-08-26 11-56-16](https://user-images.githubusercontent.com/5736988/63678956-f5226680-c7f8-11e9-9c1f-021069d8dd74.png)
As you can see, there is no button for choosing a file.
The library version is 0.6.0

**Comment by chenjr0719** [comment]
Hi @artemnesterenko 
The button will show up after click `Try it out`.

**Comment by artemnesterenko** [comment]
Oh, I've missed it. Thanks!
