### ISSUE TITLE
not support gino Model entity

### ISSUE THREAD

**Issue by beruhan** [huge-success/sanic-openapi#135]
I have a gino model like this:
```
class Student(db.Model):
    id=Column('id', VARCHAR(30), primary_key=True, doc="student id")
    name=Column('name', VARCHAR(30), doc="student name")
```
I use Student as the fllows:
```
@vuln_poc_bp.get("/")
@doc.summary("list all students")
@doc.produces([Student], content_type="application/json")
async def list_student(request):
    """list all students"""
    all_students = await Student.query.gino.all()
    return json(all_students , ensure_ascii=False)
```
the api doc can't display the model,can any one has same good ideas to solve?

**Comment by chenjr0719** [comment]
Hi there,

I'm afraid that `Sanic-OpenAPI` cannot support `gino`.  This is a limitation of `Sanic-OpenAPI` because `Sanic-OpenAPI` cannot **serialize** the object from `gino`. In the current implementation, `Sanic-OpenAPI` only support built-in class like `dict`, `list`, 'int`, etc.
