### ISSUE TITLE
[Feature Request]How to paginate the response body data or limit num by POST request?

### ISSUE THREAD

**Issue by gensuineixin** [huge-success/sanic-openapi#137]
I want to paginate the response body data,when i use POST request method, what can i do?

**Comment by chenjr0719** [comment]
Hi @gensuineixin 

I think this is a good question when using Sanic. But this project is focused on how to provide API docs, maybe you can post your question on Sanic's [community forum](https://community.sanicframework.org/) instead.

**Comment by gensuineixin** [comment]
Yes，I mean on the sanic-openapi  *.*.*.*:8000/swapper page,the Response item.
