### ISSUE TITLE
‘fetch error' will be prompted when 'name' is used as the field name in the model and the model is referenced in consumers

### ISSUE THREAD

**Issue by adiugy** [huge-success/sanic-openapi#156]
**To Reproduce**
##model##
class User:
    name = doc.String
    password = doc.String

##user_blueprint##
@blueprint.put('/login')
@doc.consumes(models.User, location='body', content_type='application/json')

**Environment (please complete the following information):**
 - OS: Windows
 - Version :0.6.1

**Comment by chenjr0719** [comment]
Hi there,

It is work on my laptop.
![image](https://user-images.githubusercontent.com/13619684/72127079-76922400-33a9-11ea-8410-bd573315ce59.png)

Verified with this code snippet:
```python
from sanic import Sanic
from sanic.response import json
from sanic_openapi import swagger_blueprint, doc

app = Sanic()
app.blueprint(swagger_blueprint)


class User:
    name = doc.String
    password = doc.String


@app.route("/")
@doc.consumes(User, location="body", content_type="application/json")
async def test(request):
    return json({"hello": "world"})


if __name__ == "__main__":
    app.run(debug=True)

```

I remember I met the same issue in old version but I think it is already fix.
You can check related source code:https://github.com/huge-success/sanic-openapi/blob/c7b96bf0df7112689119f8dded49a39901b06134/sanic_openapi/doc.py#L130

**Comment by adiugy** [comment]
Thank you very much for your answer
But I ran into some problems after updating to 0.6.1
I tried the sample you provided and found the same mistake
I think there's something wrong with my environment,
but I can't solve it
Can you help me with this problem
Thank you in advance!
This is my environment.yml
[environment.zip](https://github.com/huge-success/sanic-openapi/files/4052795/environment.zip)

**Comment by AtomsForPeace** [comment]
@chenjr0719 Is this also a windows/ujson bug like in #155?

**Comment by chenjr0719** [comment]
I think this issue is related to windows/ujson issue. And I just confirm there is another issue when using the new version of ujson in #168.
