### ISSUE TITLE
[Feature Request] Add CI for windows

### ISSUE THREAD

**Issue by AtomsForPeace** [huge-success/sanic-openapi#160]
As mentioned in #155, we need to add tests for windows users regarding ujson and other differences. 
Here is how sanic does it: https://github.com/huge-success/sanic/blob/784d5cce5234933a5af36b668c8ffce1af4af91a/tox.ini#L6-L8

**Comment by AtomsForPeace** [comment]
When the test requirements are installed, the requirements of sanic are also installed and these include ujson and uvloop. 
One easy solution would be to use requirement.txt files, define exactly what requirements we need and then use pip install --no-deps.

**Comment by chenjr0719** [comment]
I have some ideas about how to modify our `tox.ini` to meet this requirement. But, I will wait until #151 is merged if you don't mind. :grimacing:

**Comment by AtomsForPeace** [comment]
Of course
