### ISSUE TITLE
[Bug] Sanic 19.12 and sanic-openapi produce unexpected keyword error

### ISSUE THREAD

**Issue by AWegnerGitHub** [huge-success/sanic-openapi#161]
**Describe the bug**
Update sanic to the 19.12.x branch (either .0 or .2 currently show the problem). When launching sanic with sanic-openapi, the following error is emitted:

```
TypeError
_run_request_middleware() got an unexpected keyword argument 'request_name'
Traceback (most recent call last):

File /usr/local/lib/python3.7/site-packages/sanic/app.py, line 946, in handle_request

request, request_name=name

TypeError: _run_request_middleware() got an unexpected keyword argument 'request_name' while handling path /swagger
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6462439/72382580-2edc0700-36df-11ea-96ba-ff77f7d20ad4.png)

**To Reproduce**
Update sanic to the 19.12.x branch (either .0 or .2 currently show the problem). Visit the `/swagger` endpoint to see the above error in the browser.

**Expected behavior**
No middleware error should be emitted. 

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser Does not matter, error is server side
 - Version Sanic 19.12.0 or 19.12.2

This appears to be related to https://github.com/huge-success/sanic/issues/1749

**Comment by chenjr0719** [comment]
Hi @AWegnerGitHub 

Sorry for the late reply.
I haven't met this issue when using `tox` to test with `19.12.x`. Could you provide the version of python you are using and your dependencies(`pip freeze`)?
