### ISSUE TITLE
[Bug]Getting error on response from doc.py function

### ISSUE THREAD

**Issue by ray-t1** [huge-success/sanic-openapi#163]
I’ve been using Sanic on my GCP instance for two months now, however i had to restart it and all my configuration went blown.

Trying to reinitialize it, i got this error:

Traceback (most recent call last):
0|server | File “/opt/soporteventasdiemo/port/server.py”, line 160, in 
0|server | async def partner_add(request, token:Token):
0|server | File “/usr/local/lib/python3.7/dist-packages/sanic_openapi/doc.py”, line 332, in inner
0|server | route_specs[func].response.append((status_code, routefield))
0|server | TypeError: unhashable type: ‘list’

I’ve tried reinstalling dependencies but nothing works, anyone has faced this issue before?

**To Reproduce**

@doc.tag("Sales Partners")
@doc.summary("JWT Req | Add Diemo sales partner")
@doc.consumes(SalesPartnerReq, location="body", content_type='application/json')
@doc.produces(SalesPartnerResp, content_type='application/json')
@doc.response(200, SalesPartnerResp, description="Good response")
@doc.response(401, {"message": str}, description="Unauthorized")
@app.route('/partner/add',['POST','OPTIONS'])
@jwt_required
async def partner_add(request, token : Token):

**Expected behavior**
Sanic server start.

**Environment (please complete the following information):**
- GCP Ubuntu 18.04.4

**Comment by koug44** [comment]
I have the same issue with Sanic 19.12. I don't have any error with Sanic 18.12

**Comment by koug44** [comment]
More usable information:

`Traceback (most recent call last):
  File "src/main.py", line 301, in <module>
    async def alive_check(request):
  File "/home/dalexandre/.local/lib/python3.8/site-packages/sanic_openapi/doc.py", line 275, in inner
    route_specs[func].exclude = boolean
TypeError: unhashable type: 'list'
`
I can start my app by commenting all _@doc.exclude(True)_ lines

**Comment by koug44** [comment]
I've deleted my comment as I'm not sure it's exactly the same issue.

@ray-t1 try to move the @doc lines after @app.route declaration

**Comment by chenjr0719** [comment]
Hi @ray-t1, I apologize for my very late response. 😅 
About this issue, please move `@app.route('/partner/add',['POST','OPTIONS'])` before other decorator. All decorators from Sanic-OpenAPI can only apply to Sanic’s route. So, please make sure all the decorator is behind `app.routet()`, thanks.

I'm going to close this issue first, and if you still have issues, please feel free to reopen it.

**Comment by ray-t1** [comment]
> Hi @ray-t1, I apologize for my very late response. 
> About this issue, please move `@app.route('/partner/add',['POST','OPTIONS'])` before other decorator. All decorators from Sanic-OpenAPI can only apply to Sanic’s route. So, please make sure all the decorator is behind `app.route()`, thanks.
> 
> I'm going to close this issue first, and if you still have issues, please feel free to reopen it.

This worked perfectly! Thanks Jacob
