### ISSUE TITLE
[Bug] Is there a way to change the base path?

### ISSUE THREAD

**Issue by jeongmincha** [huge-success/sanic-openapi#165]
I know it is not a bug, but I need to get your help :)
How can I change the base path from ./swagger to another thing?
I want to change it like /api or /v2, etc.

**Comment by denisovkv** [comment]
Hello! Most likely this issue could help you https://github.com/huge-success/sanic-openapi/issues/131

**Comment by chenjr0719** [comment]
Hi @jeongmincha , as @denisovkv mentioned, you can use `swagger_blueprint.url_prefix` to change the endpoint of swagger doc. Here is an example:
```python
from sanic import Sanic
from sanic_openapi import doc, swagger_blueprint

app = Sanic("sanic_openapi")
swagger_blueprint.url_prefix = "/api/swagger"
app.blueprint(swagger_blueprint)
.
.
.
```

I'm going to close this issue first, and if you have any issues about changing the base path, please reopen this issue. 🙏
