### ISSUE TITLE
[Bug] attribute name "name" conflict in consumes body 

### ISSUE THREAD

**Issue by bolshoydi** [huge-success/sanic-openapi#168]
**Describe the bug**
When you want add custom object (class) with
attribute name "name" it  conflicts with "name" param in `@doc.consumes` body.
* breakpoint screenshot from [this](https://github.com/huge-success/sanic-openapi/blob/master/sanic_openapi/swagger.py#L164-L179) point
![image](https://user-images.githubusercontent.com/7124306/79075746-5736ca00-7cfd-11ea-8176-c14e67815d27.png)

And if `name` is not JSON serializable object loading of spec will fail. 

**To Reproduce**
Describe some scheme you want o add as `POST` request  body.
Let say attr `name` it something not JSON serializable (e.g. datetime object)
```python
class MySchemaClass:
    name = datetime.now()  # whatever object not JSON serializable
    some_another_filed = 200
```
* describe view
```python
from sanic.response import HTTPResponse
from sanic.views import HTTPMethodView

class SomeView(HTTPMethodView):

    @doc.summary('Some description')
    @doc.description('Some description but much longer that previous one')
    @doc.consumes(MySchemaClass, location='body')
    @doc.response(200, {'data':{'response':200}}, description='some view OK respinse')
    async def post(self, request: TrackedRequest) -> HTTPResponse:
        ...
```
**Screenshots**
* Got this
![image](https://user-images.githubusercontent.com/7124306/79075483-d0352200-7cfb-11ea-89a4-d17d08bcff7b.png)
* Traceback
`TypeError: datetime.datetime(2020, 4, 12, 20, 23, 48, 984394) is not JSON serializable`

**Expected behavior**
Expected to load `spec` properly, with model description.
![image](https://user-images.githubusercontent.com/7124306/79075893-45095b80-7cfe-11ea-87ee-d85bd281aeb0.png)

![image](https://user-images.githubusercontent.com/7124306/79075915-6ec28280-7cfe-11ea-85fc-dc4ed4baa31e.png)

**Environment (please complete the following information):**
 - OS: [OS-X Catalina]
 - Browser [chrome]
 - Version [e.g. 0.6.1]
- Python 3.7 \ 3.8.

**Comment by chenjr0719** [comment]
Hi @bolshoydi, thanks for your report. I think this also related to `ujson` library. When using `ujson==1.35`, I didn't meet this issue. But when using `ujson>=2.0.0`, this issue happened.

After check the `swagger_blueprint._spec`, I think the name in parameters is not correct. Here is the example `swagger_blueprint._spec`:
```python
{'swagger': '2.0', 'info': {'version': '1.0.0', 'title': 'API', 'description': '', 'termsOfService': '', 'contact': {'email': None}, 'license': {'name': None, 'url': None}}, 'schemes': ['http'], 'host': None, 'basePath': None, 'securityDefinitions': None, 'security': None, 'definitions': {'User': {'type': 'object', 'properties': {'id': {'type': 'integer', 'format': 'int64'}, 'name': {'type': 'string'}}}}, 'tags': [], 'paths': {'/api/users': {'get': {'operationId': 'list_users', 'summary': 'List users', 'consumes': ['application/json'], 'produces': [None], 'parameters': [], 'responses': {'200': {'schema': {'type': 'array', 'items': {'$ref': '#/definitions/User'}}}}}, 'post': {'operationId': 'list_users', 'summary': 'Create a user', 'consumes': ['application/json'], 'produces': ['application/json'], 'parameters': [{'required': False, 'in': 'body', 'name': <class 'sanic_openapi.doc.String'>, 'schema': {'$ref': '#/definitions/User'}}], 'responses': {'200': {}}}}}}
```

To fix this issue, I think we can check is the consumer a class or not here to avoid this issue:
https://github.com/huge-success/sanic-openapi/blob/0aa81c83754767c78444c3d01d548305858d8a22/sanic_openapi/swagger.py#L179-L181

to:
```python
"name": consumer.field.name
if not isinstance(consumer.field, type)
and hasattr(consumer.field, "name")
else "body",
```

Could you make a PR to help me fix this issue? 🙏

**Comment by bolshoydi** [comment]
@chenjr0719  Yes, i will try fix this.  I have already made commit, but it crashed 12 tests, where name atr checks exist.

**Comment by chenjr0719** [comment]
Since #170 has been merged, close this issue.
