### ISSUE TITLE
[Feature Request] Add ability to create descriptions for parameters

### ISSUE THREAD

**Issue by AWegnerGitHub** [huge-success/sanic-openapi#171]
**Is your feature request related to a problem? Please describe your use case.**
Allow users a way to provide a description or prose for a parameter. Sometimes, a description is warranted for specific parameters and being able to add that would be helpful.

**Describe the solution you'd like**
A way to add a description to a parameter.

**Additional context**
![image](https://user-images.githubusercontent.com/6462439/80494227-0d202c00-892c-11ea-94cc-25aa26aa5ee1.png)

Using this image from the docs as an example, I'd like to be able to describe to the user what `X-API-VERSION` means and possible values in the description column. Maybe some details about trade-offs between specific versions or information about when an older version will be sunset.

**Comment by chenjr0719** [comment]
Hi @AWegnerGitHub, I think you can add description by:
```
from sanic import Sanic
from sanic_openapi import doc, swagger_blueprint

app = Sanic("test")
app.blueprint(swagger_blueprint)


@app.get("/")
@doc.consumes({"X-API-VERSION": doc.String("The version of API")}, location="header")
async def test(request):
    return {}


app.run()

```

And it will looks like:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/13619684/84973545-ed4efc80-b153-11ea-861f-5d80471bb7d5.png">

Please have a try. 😃 And, I will close this issue first. If you have any questions, please feel free to reopen it.
