### ISSUE TITLE
[Bug]TypeError: Object of type Spec is not JSON serializable 

### ISSUE THREAD

**Issue by guifa2015** [huge-success/sanic-openapi#172]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13930091/83243421-74055f00-a1d0-11ea-86b4-a37e2c13495a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/13930091/83241829-fc363500-a1cd-11ea-9a19-acf724aa6da5.png)

![image](https://user-images.githubusercontent.com/13930091/83241806-f3ddfa00-a1cd-11ea-9957-a881255e66da.png)

**Environment (please complete the following information):**
 - OS: windos10
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 0.5.3]
 - sanic-version 20.3.0
**Additional context**
Add any other context about the problem here. This might be how to fix this bug or some hint to fix it.

**Comment by chenjr0719** [comment]
Hi @guifa2015, this issue is due to the new release of `ujson`. Please try to use `ujson==1.3.5` instead. I will close this issue first and if you need more help, please reopen and let me know your issue. 😄

**Comment by mfekadu** [comment]
I tried `pip install usjon==1.35` and the bug was fixed.

I wonder why `3.0.0` is buggy in that way?

**Comment by chenjr0719** [comment]
The new release of `ujson` changes its behavior so the JSON serialization not working as before. This serialization already fixed in #157 but we haven't released this fixed version to PyPI yet.
