### ISSUE TITLE
[Feature Request] Support OpenAPI 3

### ISSUE THREAD

**Issue by ioggstream** [huge-success/sanic-openapi#178]
**Is your feature request related to a problem? Please describe your use case.**

Support OpenAPI 3.

**Describe the solution you'd like**
A configurable way to generate OpenAPI3 documentation.

**Additional context**
A basic working feature can even produce and convert OAS3 from OAS2.
To support OAS3 features (eg. jsonschema, oauth scopes, multiple content-types ... ) a more radical work should be done.

**Comment by ruckc** [comment]
please reopen this

**Comment by ioggstream** [comment]
@ronnyhel FYI

**Comment by ruckc** [comment]
@ioggstream @chenjr0719 - i've tried getting this PR to build with the tox config, but i can't figure out the black / isort incompatibility with the imports, I've tried following black's [guide](https://black.readthedocs.io/en/stable/compatible_configs.html) for it with no solution.
