### ISSUE TITLE
[Feature Request] Add configuration to turn off swagger in production environment

### ISSUE THREAD

**Issue by wei-hai** [huge-success/sanic-openapi#186]
Add some flag in the configuration to turn off the swagger page or show no URI.

**Comment by denisovkv** [comment]
Hello! What about next workaround:
```    
if settings.DEBUG:
    app.blueprint(swagger_blueprint)
```
Don't think this feature is relevant

**Comment by ahopkins** [comment]
I would agree. Thank you for the thoughts but this doesn't seem like a feature that needs internal support.
