### ISSUE TITLE
[Feature Request] Add description to path parameters

### ISSUE THREAD

**Issue by ExpLog** [huge-success/sanic-openapi#188]
I've started using sanic-openapi to document our APIs and I'm currently struggling to add a description to a route's path parameter. Since there's no documentation on how to do this, I decided to open this issue to see if I'm just missing something or if this is a legitimate feature request.

For example, I have a route that looks like this:
```python
bp = Blueprint('foo', url_prefix='/foo')

@bp.route('/<foo_id>/bar, methods=['GET', 'OPTIONS'])
async def get_foo_bar_by_id(request, foo_id):
    return {'bar': 'something', 'foo': foo_id}
```

The Swagger page will automatically generate a parameter for this endpoint with the correct name, but no description, as you can see in the attached screenshot.

![Screenshot 2020-08-11 at 14 54 18](https://user-images.githubusercontent.com/4949475/89906167-f358db00-dbe2-11ea-9ee3-786840b171f5.png)

I've tried adding the following annotation to the endpoint:
```python
@doc.consumes(doc.String(description='The description', name='foo_id'), location='path', required=True)
```

However, the annotation above changes nothing. The automatically created parameter is still being shown with an empty description.

If this feature doesn't currently exist, I'd love to have a way to override the path parameters default description, as I want to explain exactly what should go in there. Currently, my workaround is to simply add that explanation to the description.

**Comment by opensorceror** [comment]
bump
