### ISSUE TITLE
Offline/firewalled mode

### ISSUE THREAD

**Issue by choobinejad** [huge-success/sanic-openapi#24]
There are several pointers in `swagger-ui.js` and `swagger-ui-bundle.js` to `https://online.swagger.io/validator`. These pointers cause the swagger UI to freeze. 

Would it be possible to document "offline deployment" instructions, or even provide a configuration for whether or not the UI should try to access resources on external domains?

**Comment by Typhon66** [comment]
Would have to look into this.

**Comment by fredyw** [comment]
Disabling online validator can be done by setting `validatorUrl` to `null` in `SwaggerUIBundle` of `index.html`. I'm not sure if there's an easy way to configure this in Python, though.

**Comment by jasper9** [comment]
+1 for this

**Comment by hampsterx** [comment]
https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

this is an option as I don't think templating index.html is suitable.

```
configUrl: 'swagger-config.yaml',
```

then have a route for it in swagger.py

```
@blueprint.route('/swagger-config.yaml')
@doc_route(exclude=True)
def config(request):

    options = {}

    if hasattr(request.app.config, 'API_VALIDATOR_URL'):
        options['validatorUrl'] = getattr(request.app.config, 'API_VALIDATOR_URL')

    return json(options)
```

@ahopkins @DirkGuijt I can do a PR for this if happy with this approach. I am in need of this solution also as many of our APIs are internal.

**Comment by LTMenezes** [comment]
+1 for this.

I think a quick solution to this issue would be to add another option in the "app.config" in order to make the validator URL customizable. This way we would enable sanic-openapi users to disable the validation or to provide a custom validator URL.

What do you guys think about this approach? I would be happy to submit a PR for this.
@hampsterx @chenjr0719

**Comment by hampsterx** [comment]
@LTMenezes go for it~

**Comment by chenjr0719** [comment]
@LTMenezes Sounds good.
