### ISSUE TITLE
Support for specifying Bearer Token in Authorization Header

### ISSUE THREAD

**Issue by vasagan** [huge-success/sanic-openapi#25]
Hello there,

I am not sure if support for this already exists. As far as i looked, i couldn't find.

**Comment by Typhon66** [comment]
@vasagan Looks like @kbfu has a pull request up to add header support that is currently broken. Once that is fixed i'll be happy to merge it in.

**Comment by cptm0rgan** [comment]
IS there any progress on this topic?

**Comment by DirkGuijt** [comment]
My pull request #58 supports this. It has been open for a while not though...

**Comment by DirkGuijt** [comment]
this was fixed in #58
