### ISSUE TITLE
the api can't show the parameters using @doc.consumes

### ISSUE THREAD

**Issue by xiaobaojiang** [huge-success/sanic-openapi#29]
code:
```
@app.route("/new_moment/<uid:int>",methods=["POST"])
@doc.consumes({
    "type":int,
    "res_json":str,
    "words":str,
    "location":str
})
def test():
```
download the "spec.json" file and find the method parameters description: 
`"post":{"parameters":[{"format":"int64","in":"path","required":true,"type":"integer","name":"uid"},{"in":"body","name":"body","properties":{"res_json":{"type":"string"},"location":{"type":"string"},"words":{"type":"string"},"type":{"format":"int64","type":"integer"}},"type":"object"}]`
so . firstly I want to konw the parameters format is correct ?  secondly I want to konw where I can find the "spec.json" datas standard description . thanks.

**Comment by Typhon66** [comment]
@EveryIsNormal Can you check version 0.3.0? This seems to be working for me.

**Comment by silver8ack** [comment]
confirmed, this is broken in 0.4.0.  Works in 0.3.0(now if I can figure out how to get in in the body instead of query).

**Comment by silver8ack** [comment]
Just realized it works if you use a class instead of a dict..

```
class ModelCreate:
    name = str
    schema = dict

@doc.consumes(ModelCreate, location='body')
```
