### ISSUE TITLE
securityDefinitions and parameters

### ISSUE THREAD

**Issue by njordr** [huge-success/sanic-openapi#3]
Hi.

Any chance to include the securityDefinitions section?

Also, is there a way to define the parameters, defining if they are from URL query part, form, body, etc?

**Comment by tclarke** [comment]
Second question is a duplicate of #9

**Comment by Typhon66** [comment]
@njordr We do have a PR up to add headers to the docs. With that we could probably also add in the securityDefinitions

**Comment by hampsterx** [comment]
securityDefinitions resolved in #58 and params is dup of #9 as noted.
