### ISSUE TITLE
how to use this extensions with HTTPMethodView?

### ISSUE THREAD

**Issue by hsz1273327** [huge-success/sanic-openapi#42]
I try to use sanic-openapi with HTTPMethodView like blow:

```python
class EmailSource(HTTPMethodView):

    @doc.summary("Fetches a user by ID")
    @doc.produces({ "user": { "name": str, "id": int } })
    def get(self, request):
       
        return json({"message":'I am get method'})
```

but `/swagger` can not show the docs
![image](https://user-images.githubusercontent.com/7850148/30201234-8b559ce4-94ac-11e7-9110-f745135ee75e.png)

**Comment by Feeeenng** [comment]
hi.l am  the some  problem. do you resolved ?

**Comment by mholiv** [comment]
Is this a supported use case? Also running into this issue.

**Comment by aranya-danno** [comment]
+1

**Comment by junxi3166** [comment]
+1

**Comment by logileifs** [comment]
+1

**Comment by Caoyiii** [comment]
Hope it update soon.
