### ISSUE TITLE
Produces not showing up on Swagger UI?

### ISSUE THREAD

**Issue by LeonP92** [huge-success/sanic-openapi#50]
I'd assume using `doc.produces({...})` would have something show up in the UI but nothing is showing up.

**Comment by daenney** [comment]
I can second this, in 0.4.0 models don't get translated into definitions and the `produces` decorator doesn't work correctly (probably as a consequence of it). I've reverted to 0.3.0 which does what you'd expect.

**Comment by joar** [comment]
@daenney A possible workaround is:

```python
@doc.route(produces=Car, ...)
```

**Comment by clintharris** [comment]
same issue with `0.4.0`. @joar's work-around worked, though (thanks).

**Comment by imnisen** [comment]
same issue with `0.4.0`.

**Comment by chenjr0719** [comment]
`@doc.produces()` is worked after merge #58, close this issue.
