### ISSUE TITLE
No support custom status code in responses

### ISSUE THREAD

**Issue by olexandr-klymenko** [huge-success/sanic-openapi#51]
There should be a way to configure custom (not 200) status code in response like in flask-restplus:
from flask_restplus import Namespace
ns = Namespace('Wallet')
...
@ns.response(201, 'Wallet created')
...
@ns.response(404, 'Wallet not found')

something like:
@doc.response(404, 'Wallet not found')

**Comment by oddjobz** [comment]
Hi, I've just submitted a PR for my implementation of this;
```
def response(code, description=None, examples=None):
```

**Comment by hampsterx** [comment]
fixed in #58
