### ISSUE TITLE
Documenting passed parameters

### ISSUE THREAD

**Issue by oddjobz** [huge-success/sanic-openapi#55]
Hi, can someone tell me whether there is an easy way of documenting path parameters, it seems to be eluding me if it's there .. for example;
```python
@warc_blueprint.get('/open/<file_name:string>', strict_slashes=True)
@doc.summary('Open a connection to a file')
async def open_get(request, file_name) ...
```
Essentially I'm looking to be able to associate a description with "file_name" so I can display it on the Swagger UI next to the name/type .. (?) Maybe something like this;
```python
@doc.parameter('file_name', 'The name of the file to open')
```

**Comment by oddjobz** [comment]
No interest

**Comment by koug44** [comment]
I'm also looking for something like this

**Comment by ExpLog** [comment]
Me too, I actually just created a new issue requesting this before finding this one. Any news on this?
