### ISSUE TITLE
How to change the route of spec.json

### ISSUE THREAD

**Issue by sunhailin-Leo** [huge-success/sanic-openapi#62]
![_20180327214555](https://user-images.githubusercontent.com/17564655/37971328-3d2c1454-3208-11e8-9147-ca0615d280a7.png)

Change the swagger route it work, but openapi/spec.json route still in root route.

Picture is here.
![_20180327214851](https://user-images.githubusercontent.com/17564655/37971499-ae35b15a-3208-11e8-8aad-3b0495670dbd.png)

How can I change it? :simple_smile:

**Comment by hampsterx** [comment]
#58 
> fixed the issue where swagger always expects the openapi/spec.json path to be at the root of the url path

just need to wait till xmas to get it merged sigh

**Comment by DirkGuijt** [comment]
Christmas came early this year :P

**Comment by hampsterx** [comment]
thanks santa Dirk~
