### ISSUE TITLE
Having the password exposed?

### ISSUE THREAD

**Issue by TheGrandmother** [huge-success/sanic-openapi#70]
I don't really know the nature of how pypi handles authorization, but is it really a good idea to have the password made public here?

https://github.com/huge-success/sanic-openapi/blob/7b5cbf12726d9e35a448aafedde97a36f1aa20f8/.travis.yml#L12

**Comment by ahopkins** [comment]
Of course! And, while we are at it, the password to my bank account is `password123`. That's secure enough, right?

**Comment by ahopkins** [comment]
https://docs.travis-ci.com/user/encryption-keys/
