### ISSUE TITLE
Exclude routes

### ISSUE THREAD

**Issue by endafarrell** [huge-success/sanic-openapi#75]
#21 is closed, but its fix only half-works: 

* routes excluded with ``@doc.route(exclude=True)`` do not appear in the swagger UI, but,
* they are listed (although empty) in the ``/openapi/spec.json``

My expectation is that an "excluded" route would not appear in either the ``openapi/spec.json`` or the swagger UI.

**Comment by hampsterx** [comment]
looks like it just needs a one liner to fix (line 144) ..

```
        if methods:
            paths[uri_parsed] = methods
```

(ie the *if* line)
