### ISSUE TITLE
@doc.pruduces not working

### ISSUE THREAD

**Issue by gangtao** [huge-success/sanic-openapi#76]
`@dataset_svc.get('/datasets', strict_slashes=True)`
`@doc.summary('list all datasets')`
`@doc.produces([{"name": str, "id": str, "type": str}])`
`async def list_datasets(request):`
`    dataset_class = get_dataset_class('CSV')`
`   try:`
`        datasets = dataset_class.list_datasets()`
`        return response.json(datasets, status=200)`
`    except Exception:`
`        return response.json({}, status=500)`

there is nothing produced, what could be the reason?

**Comment by gangtao** [comment]
it is a duplicated issue of https://github.com/huge-success/sanic-openapi/issues/50
@doc.route() is the workaround

**Comment by chenjr0719** [comment]
`@doc.produces()` is worked after merge #58, close this issue.
