### ISSUE TITLE
spec link broken due to relative url

### ISSUE THREAD

**Issue by hampsterx** [huge-success/sanic-openapi#79]
@DirkGuijt #58 using relative link has caused a small side effect.

https://github.com/swagger-api/swagger-ui/issues/4107

testing using (latest) swagger 3.18.3 seems to work using "./" prefix as suggested in issue above. So quick fix is to upgrade from 3.9.2 I guess

**Comment by chenjr0719** [comment]
@hampsterx I think I can send a PR to upgrade `swagger-ui` to the latest release(3.22.0), if you don't mind.

**Comment by hampsterx** [comment]
cool, go for it, i had a look but wasn't sure how to get the dist seems its npm package so wasn't sure how it was done before and or if it had changed.
