### ISSUE TITLE
Documentation of GET request query params

### ISSUE THREAD

**Issue by maxpagels** [huge-success/sanic-openapi#9]
Is it somehow possible to document the required query strings (note: not URL path params) and their types for GET requests? This line https://github.com/channelcat/sanic-openapi/blob/8a7b77f0fbda15061a8132c8a5c163f6ea82afcb/sanic_openapi/openapi.py#L103 suggests that @doc.consumes can only be used for HTTP verbs other than GET and DELETE.

**Comment by channelcat** [comment]
I've set it up so consumes will go to query string on GET and DELETE, though I think we still need a plan for POST requests.  maybe:
```python
@doc.consumes({ 'things': str, 'stuff': str }, from='query')
@app.post('/coolstuff')
def cool_stuff(request):
    ...
```
What do you think?

**Comment by maxpagels** [comment]
@channelcat That syntax looks to be pretty self-explanatory. How about POST request with a body _and_ query params? Two separate @consumes decorators?

Not that POST endpoints use both very often, but it's still technically valid.

**Comment by tclarke** [comment]
Very interested in this feature.

**Comment by manuelsotoma** [comment]
is there any news about this feature?
very interested as well

**Comment by Typhon66** [comment]
@manuelsotoma Want to get this done soon. The plan might be to add the "from" parameter to specify where something is in all cases.

**Comment by RemiDesgrange** [comment]
Any improvement on that ? note that you cannot use `from` since it's a reserved keyword
