### ISSUE TITLE
Pypi update version

### ISSUE THREAD

**Issue by raphaelauv** [huge-success/sanic-openapi#92]
The new release 0.5.1 is not yet on pypi ( and the 0.5.0 is broken )

https://pypi.org/project/sanic-openapi

Do you know how to update it ? @ahopkins

**Comment by ahopkins** [comment]
Will take a look tomorrow. 👍

**Comment by raphaelauv** [comment]
hello , pypi is still not updated , can I help ?

**Comment by ahopkins** [comment]
`__version__` was still set to `0.5.0` so nothing deployed. I bumped it to `0.5.2`. Should hopefully kick it into gear.
